---  
- name: install libfontconfig1
  apt:
    pkg:
      - adduser
      - libfontconfig1
    update_cache: true
    state: latest

- name: copy grafana-enterprise_10.0.3_amd64.deb
  copy:
    src: grafana-enterprise_10.0.3_amd64.deb
    dest: /tmp
      
- name: install grafana
  apt:
    deb: "/tmp/grafana-enterprise_10.0.3_amd64.deb"
  notify: start grafana

- name: start handlers
  meta: flush_handlers

- name: copy grafana datasource config
  template:
    src: grafana-prometehus-datasource.yml.j2
    dest: "/etc/grafana/provisioning/datasources/prometheus.yml"
    owner: root
    group: grafana
  notify: restart grafana
    
- name: copy grafana dashboard
  copy:
    src: NGINX Servers Metrics.json
    dest: "/etc/grafana/provisioning/dashboards/"
    owner: root
    group: grafana
    
- name: import dashboard
  grafana_dashboard:
    grafana_url: "http://{{ hostvars['grafana-host'].ansible_host }}:3000"
    grafana_user: "admin"
    grafana_password: "admin"
    path: /etc/grafana/provisioning/dashboards/NGINX Servers Metrics.json
  notify: enable grafana