- hosts: elasticsearch
  remote_user: mashkov
  become: yes
  become_method: sudo
  roles:
    - elasticsearch

- hosts: kibana
  remote_user: mashkov
  become: yes
  become_method: sudo
  roles:
    - kibana

- hosts: webservers
  remote_user: mashkov
  become: yes
  become_method: sudo
  roles:
    - filebeat