- hosts: prometheus
  remote_user: mashkov
  become: yes
  become_method: sudo
  roles:
    - prometheus
    - node_exporter

- hosts: grafana
  remote_user: mashkov
  become: yes
  become_method: sudo
  roles:
    - grafana
    - node_exporter